### ISSUE TITLE
Incompatibility with Whistle Jester mod due "FixPluginTypesSerialization" dependency. (Whistle Jester is just too outdated)

### ISSUE THREAD

**Issue by AJAL8000** [Yinigma/EnemySkinKit#6] opened 2024-06-29 00:47 UTC
->This issue isn't specific to this mod, but I wanted to report it _just in case._ 

That dependency is causing crashes.
Hopefully it just requires a simple fix. Who knows, maybe it'll fix itself when the version comes out of beta. Idk.

**Comment by Yinigma** [comment] 2024-06-29 11:36
Thanks for keeping me posted. This mod is one of many that depends on FixPluginTypesSerialization to allow for custom content to be loaded into the game. I'm willing to bet it'll have a fix put on it by the time v55 is out. Either way, it's not an issue with _this_ mod, so I'm going to remove this issue from this repo.

**Comment by Yinigma** [comment] 2024-07-07 06:58
I'm not sure what was happening on your end. I reckon I forgot to put this dependency back in and that's what was doing it. But there doesn't seem to be anything wrong. If you wanna take the time to confirm it, if you can reproduce the bug or you run into it again, it helps a lot if you copy and paste the error in here. For now I'm going to close the issue because it appears that there's nothing wrong with the fix serialization plugin.

**Closed as completed** 2024-07-07 06:58 UTC

**Comment by AJAL8000** [comment] 2024-07-07 08:35
@Yinigma  Yes, I just noticed that it is an incompatibility with some mod, but it is curious that among several mods that I have, specifically disabling this one makes the game not crash.
![image](https://github.com/Yinigma/EnemySkinKit/assets/55171241/8c70466a-386b-47d7-a61d-d9ed734415c9)
I will be seeing these days which mod is causing the incompatibility. The only clue I see that I have is this message at the end before the crash, that "corruption" of that file only happens when the dependency is activated, simply deactivating it makes the game run normally.

**Comment by AJAL8000** [comment] 2024-07-07 17:32
@Yinigma B R U H. [Whistle Jester](https://thunderstore.io/c/lethal-company/p/WrouidInc/WhistleJester/) It is causing the game to crash since it is incompatible (somehow) with "FixPluginTypesSerialization".
I literally can't believe it, that was the last thing that would come to my mind.
I'm using the "fixed" version of that mod but it seems to still have the problem, at least for the new version.

I hope someone finds this issue and doesn't spend a lot of time looking for what mod is causing the incompatibility, since it's almost impossible to imagine it's Whistle Jester LMAO.
