### ISSUE TITLE
Problem, with the mod.

### ISSUE THREAD

**Issue by Eddieddg1** [Yinigma/EnemySkinKit#1] opened 2024-04-27 03:47 UTC
I get this after step 11. I followed the guide 1 to 1

```
Unable to update following assemblies:Packages/com.antler-shed.enemy-skin-kit/plugins/EnemySkinKit/EnemySkinKit.dll (Name = EnemySkinKit, Error = 131) (Output: C:\Users\LOLbe\AppData\Local\Temp\tmp1de62100.tmp)

[AssemblyUpdater] Failed to resolve assembly BepInEx, Version=5.4.21.0, Culture=neutral, PublicKeyToken=null. SearchPaths: C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\EnemySkinKit\plugins\EnemySkinKit, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\ref\2.1.0, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\compat\2.1.0\shims\netstandard, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\compat\2.1.0\shims\netfx, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\AssetsTools.NET, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\Markdig, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\SharpCompress, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\SharpZipLib, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.collab-proxy@2.3.1\Lib\Editor\PlasticSCM, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\EditorAssetResources, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\Assemblies, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\DotNetZip, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\YamlDotNet, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Runtime\VisualScripting.Flow\Dependencies\NCalc, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\EnemySkinKit\plugins\EnemySkinKit, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\FixPluginTypesSerialization\BepInEx\patchers\FixPluginTypesSerialization, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\Lethal Company, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\Lethal Company\plugins, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8\.Runtime, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8\Unity.Burst.CodeGen, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.testtools.codecoverage@1.2.4\lib\ReportGenerator, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.ext.nunit@1.0.6\net35\unity-custom, C:\Program Files\Unity 2022.3.9f1\Editor\Data\Managed\UnityEngine.
[AssemblyUpdater] Failed to resolve assembly BepInEx, Version=5.4.21.0, Culture=neutral, PublicKeyToken=null. SearchPaths: C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\EnemySkinKit\plugins\EnemySkinKit, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\ref\2.1.0, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\compat\2.1.0\shims\netstandard, C:\Program Files\Unity 2022.3.9f1\Editor\Data\NetStandard\compat\2.1.0\shims\netfx, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\AssetsTools.NET, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\Markdig, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\SharpCompress, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.passivepicasso.thunderkit@c63a5c279e\Editor\ThirdParty\SharpZipLib, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.collab-proxy@2.3.1\Lib\Editor\PlasticSCM, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\EditorAssetResources, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\Assemblies, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\DotNetZip, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Editor\VisualScripting.Core\Dependencies\YamlDotNet, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.visualscripting@1.9.0\Runtime\VisualScripting.Flow\Dependencies\NCalc, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\EnemySkinKit\plugins\EnemySkinKit, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\FixPluginTypesSerialization\BepInEx\patchers\FixPluginTypesSerialization, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\Lethal Company, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Packages\Lethal Company\plugins, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8\.Runtime, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.burst@1.8.8\Unity.Burst.CodeGen, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.testtools.codecoverage@1.2.4\lib\ReportGenerator, C:\Users\LOLbe\Documents\Unity Projects\My project (3)\Library\PackageCache\com.unity.ext.nunit@1.0.6\net35\unity-custom, C:\Program Files\Unity 2022.3.9f1\Editor\Data\Managed\UnityEngine. Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'BepInEx, Version=5.4.21.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at APIUpdater.Framework.Core.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'BepInEx, Version=5.4.21.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at APIUpdater.Framework.Core.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.CustomAttribute.Resolve()
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at AssemblyUpdater.Steps.MoveToNamespace.Visit(CustomAttribute customAttribute, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context)
   at AssemblyUpdater.Steps.AssemblyUpdaterStepBase.Visit(AssemblyDefinition assemblyDefinition, Context context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Unity.Cecil.Visitor.Visitor.Visit[T](T node, Context context)
   at Unity.Cecil.Visitor.Extensions.DoAccept[T](T definition, Visitor visitor)
   at Unity.Cecil.Visitor.Extensions.Accept(AssemblyDefinition assemblyDefinition, Visitor visitor)
   at AssemblyUpdater.Steps.AssemblyUpdaterStepBase.Apply(AssemblyUpdaterContext context)
   at AssemblyUpdater.Core.AssemblyUpdaterPipeline.RunUpdateRound(AssemblyUpdaterContext context)
   at AssemblyUpdater.Core.AssemblyUpdaterPipeline.Run(AssemblyUpdaterContext context)
   at AssemblyUpdater.Application.Program.UpdateAssembly(UpdateOptions config, AssemblyUpdaterContext context)
   at AssemblyUpdater.Application.Program.<>c__DisplayClass0_0.<Main>b__1(UpdateOptions o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at AssemblyUpdater.Application.Program.Main(String[] args)

UnityEditor.Scripting.APIUpdaterLogger:WriteErrorToConsole (string,object[])
UnityEditorInternal.APIUpdating.APIUpdaterManager:HandleAssemblyUpdaterErrors (System.Collections.Generic.IList`1<UnityEditorInternal.APIUpdating.AssemblyUpdaterUpdateTask>)
UnityEditorInternal.APIUpdating.APIUpdaterManager:UpdateAssemblies ()
UnityEditorInternal.APIUpdating.APIUpdaterManager:ProcessImportedAssemblies (string[])

```

**Comment by Eddieddg1** [comment] 2024-04-27 06:52
So the problem seems to be that it doesn't download bepinex with the mod.

**Comment by Eddieddg1** [comment] 2024-04-27 07:59
You can fix this by manually download the bepinex mod before step 11. But now I have this error.

`Unloading broken assembly Packages/com.antler-shed.enemy-skin-kit/plugins/EnemySkinKit/EnemySkinKit.dll, this assembly can cause crashes in the runtime`

**Comment by Eddieddg1** [comment] 2024-04-27 09:54
I can get 0.2.8 and 1.0.0 to work but not 1.0.1

**Comment by FissionMetroid101** [comment] 2024-04-27 15:27
I'm having the same issues, but I haven't managed to make any version work quite yet.  I've also had an issue when having Thunderkit import the Lethal Company dlls.  Alongside the EnemySkinKit.dll failing, I also get
`Unloading broken assembly Packages/lethalcompany/Unity.Services.QoS.dll, this assembly can cause crashes in the runtime`

**Comment by FissionMetroid101** [comment] 2024-04-28 18:50
> I'm having the same issues, but I haven't managed to make any version work quite yet. I've also had an issue when having Thunderkit import the Lethal Company dlls. Alongside the EnemySkinKit.dll failing, I also get `Unloading broken assembly Packages/lethalcompany/Unity.Services.QoS.dll, this assembly can cause crashes in the runtime`

Let it be known I am a fool and kept making the project with the standard Pipeline thinking it was defaulting to the HDRP one, however 1.0.1 still does not work.  1.0.0 is functional though.

**Comment by Yinigma** [comment] 2024-04-28 20:33
Apologies for the late reply. For some reason I didn't see the e-mail when this issue was opened.
I'll try and reproduce this from a new project and look into what's going wrong. The update from 1.0.0 to 1.0.1 was a minor fix to the code generation, and it worked fine when I updated from thunderstore, so I'm sure it's something easily fixed.
I'll look into getting BepinEx back on the manifest since that dependency apparently isn't automatically resolving too.

**Comment by Yinigma** [comment] 2024-04-28 21:30
> I'm having the same issues, but I haven't managed to make any version work quite yet. I've also had an issue when having Thunderkit import the Lethal Company dlls. Alongside the EnemySkinKit.dll failing, I also get `Unloading broken assembly Packages/lethalcompany/Unity.Services.QoS.dll, this assembly can cause crashes in the runtime`

Try getting the enemy skin registry from the thunderkit package manager in the same way you're getting the enemy skin kit. I mistakenly removed it from the skin kit's dependencies when updating it, so it wouldn't have fetched bepinEx or LethalConfig, which might be why the skin kit is throwing errors. I'm updating the manifest right now, so you could also wait for that and see if it works just following the guide again. I'll confirm that I can start a project from scratch some time later today, but I suspect that this is the fix if version 1.0.0 isn't throwing errors.

**Comment by Eddieddg1** [comment] 2024-04-29 11:55
Now when I build the mod it builds everything fine, but then removes it, and then complains that it can't find it.

**Comment by Yinigma** [comment] 2024-04-29 16:37
> Now when I build the mod it builds everything fine, but then removes it, and then complains that it can't find it.

The removal is by design since it just makes a bit of generated code you're not supposed to modify. The error messages are because unity doesn't like the way I'm getting rid of those files. It's a low-priority bug.

If the mod was created correctly, there should be a folder  called "EnemySkinKit" at the same level as your project's Assets folder. You can open a file explorer in the correct location by right clicking your Assets folder in the unity editor and selecting "show in explorer." Open the EnemySkinKit folder and see if your mod's zip file is in there. If it isn't, try creating the mod again and make sure to hit "cancel" on the error message that pops up.

**Comment by Eddieddg1** [comment] 2024-04-29 16:40
Okay, Thanks for the info!

**Comment by Yinigma** [comment] 2024-04-29 20:30
> Okay, Thanks for the info!

If your mod is working correctly, please let me know so I can close out this issue.

**Comment by Eddieddg1** [comment] 2024-04-30 02:54
My mod does not work, but I know what I did wrong, and how to fix it, I just don't have the energy.

**Comment by Yinigma** [comment] 2024-04-30 03:50
> My mod does not work, but I know what I did wrong, and how to fix it, I just don't have the energy.

Alright. I'm going to mark this as completed then.

**Closed as completed by Yinigma** 2024-04-30 03:50 UTC
Labels: bug
